INSERT INTO USER (USER_ID, NAME, PASSWORD, EMAIL, CREATED_WRITTEN_TIME) VALUES ('kses1010', 'Sunny', '123', 'kses1010@gmail.com', CURRENT_TIMESTAMP);
INSERT INTO USER (USER_ID, NAME, PASSWORD, EMAIL, CREATED_WRITTEN_TIME) VALUES ('qwerty', 'Hello', 'abc', 'hihi@naver.com', CURRENT_TIMESTAMP);

INSERT INTO QUESTION (ID, CONTENTS, CREATED_WRITTEN_TIME, TITLE, WRITER_ID, COUNT_OF_ANSWER) VALUES (1, '테스트입니다.1', CURRENT_TIMESTAMP, '테스트1', 1, 2);
INSERT INTO QUESTION (ID, CONTENTS, CREATED_WRITTEN_TIME, TITLE, WRITER_ID, COUNT_OF_ANSWER) VALUES (2, '테스트입니다.2', CURRENT_TIMESTAMP, '테스트2', 2, 0);

INSERT INTO ANSWER (ID, CONTENTS, CREATED_WRITTEN_TIME, QUESTION_ID, WRITER_ID) VALUES (1, '111', CURRENT_TIMESTAMP, '1', 1);
INSERT INTO ANSWER (ID, CONTENTS, CREATED_WRITTEN_TIME, QUESTION_ID, WRITER_ID) VALUES (2, '222', CURRENT_TIMESTAMP, '1', 2);
